### ISSUE TITLE
ERROR    InternetArchiveBackend backend caused an exception.

### ISSUE THREAD

**Issue by gerroon** [tkem/mopidy-internetarchive#66] opened 2017-10-12 02:26 UTC
I am using Mopidy 2.1.0 on Debian Testing x64

I enabled it in the config. This is what I get when I click on IArchive link in the browse section

ERROR    InternetArchiveBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/library.py", line 49, in browse
    return self.__browse_root()
  File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/library.py", line 141, in __browse_root
    fields=['identifier', 'mediatype', 'title']
  File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/client.py", line 73, in search
    return self.SearchResult(response.json())
  File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/client.py", line 87, in __init__
    self.query = result['responseHeader']['params']['q']
KeyError: u'q'

**Comment by tkem** [comment] 2017-10-12 06:51
Does this also occur on Debian stable?

**Comment by tkem** [comment] 2017-10-12 06:55
This is a probably a duplicate of #65: After some changes in the archive.org API, you need mopidy-internetarchive v2.0.3.

**Comment by tkem** [comment] 2017-10-12 07:35
See also https://discuss.mopidy.com/t/announcement-mopidy-internetarchive-v2-0-3/1665

**Closed** 2017-10-12 07:34 UTC

**Comment by gerroon** [comment] 2017-10-12 14:08
@tkem 

I am using whatevere version is provided by pip (or mopidy repo), how do I get the latest version?

**Comment by gerroon** [comment] 2017-10-12 14:10
Ok I got the upgrade from the forum post, still throws exceptions


ERROR    InternetArchiveBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/library.py", line 49, in browse
    return self.__browse_root()
  File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/library.py", line 141, in __browse_root
    fields=['identifier', 'mediatype', 'title']
  File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/client.py", line 73, in search
    return self.SearchResult(response.json())
  File "/usr/lib/python2.7/dist-packages/mopidy_internetarchive/client.py", line 87, in __init__
    self.query = result['responseHeader']['params']['q']

**Comment by Minda1975** [comment] 2019-05-22 15:12
Same problem here (with version 2.0.0 and version 2.0.3-1
